---
title: "CostBuffers"
author: "María (modified by Indra)"
date: "inicio: 20 de octubre de 2016"
output: html_document
---
Last version: `r Sys.Date()`

```{r, echo=F}
library(knitr)
opts_knit$set(root.dir ="/home/indra/Dropbox/carpeta sin título/Datos_Indra")
# setwd("/home/indra/Dropbox/carpeta sin titulo/Carpeta_Indra")
ori.par <- par()
```

```{r set-options, echo=FALSE}
options(width = 1400)
```

# Load inputs
### Load packages
```{r loadpackages, tidy=T}
# library(rgeos) # para calcular áreas etc
library(raster) # para importar shapefiles etc
# library(rgdal) # para cambiar proyecciones de capas etc
library(gdistance) # para calcular
```

### Load DEM (Digital Elevation Model)
```{r}
dem <- raster("GIS/DEMbasins.tif")
```

### Load INVENTARIOS
```{r loadinventarios, cache=T}
inv.raw <- read.table("inventarios.csv", header=T, sep=",")
inv <- unique(inv.raw[,c("inv", "lon", "lat")])[,c("lon", "lat")]
ninv <- unique(inv.raw$inv)
rownames(inv) <- ninv
# transform numeric format of inventarios coordinates to spatial object
coordinates(inv) <- ~lon+lat
proj4string(inv) <- CRS("+proj=longlat +datum=WGS84")
```

### Load CLIMA
```{r loadclima, cache=T}
climest.raw <- read.table("clima.estaciones.csv", header=T, sep=",")
climest <- unique(climest.raw[,c("est", "lon", "lat")])[,c("lon", "lat")]
nclimest <- unique(climest.raw$est)
rownames(climest) <- nclimest
# transform numeric format of inventarios coordinates to spatial object
coordinates(climest) <- ~lon+lat
proj4string(climest) <- CRS("+proj=longlat +datum=WGS84")
```

# Calculate
### Create ASYMETRICAL transition layer
```{r}
# directions: es el nº de vecinos con el que conecta
# symm: if moving A->B and B->A costs the same
# transitionFunction: should be NOT-commutative such as f(i,j) != f(j,i)
altDiff <- function(x){ x[1] - x[2] }
mydir <- 4
tr1 <- transition(x = dem, directions = mydir, symm=F, transitionFunction =altDiff)
# tr1 <- geoCorrection(tr1)
adj <- adjacent(dem, cells=1:ncell(dem), pairs=TRUE, directions=mydir)
speed <- tr1
up <- -1/1.5 # (-1/1.5) # cuanto más cerca de 1 menos penaliza la cuesta arriba
flat <- 1
down <- 2 # cuanto más cerca de 1 menos facilita la cuesta abajo
# down/-up # veces más fácil bajar q subir
speed[adj] <- ifelse(speed[adj]==0, flat,
                     ifelse(speed[adj]<0, up * (speed[adj][speed[adj]<0]),
                            ifelse(speed[adj]>0, down * (speed[adj][speed[adj]>0]), 0)))
```

### Calculate cost matrix
```{r}
cost.inv <- costDistance(x = speed, fromCoords = inv, toCoords = inv)
write.table(cost.inv, file = "results/cost.all.csv", quote = F, sep = ",", row.names = T)
# cost.cli <- costDistance(x = tr1, fromCoords = inv, toCoords = climest)
```

